### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by zaoqi** [jakerockland/Swisp#39] opened 2017-12-10 10:12 UTC
```scheme
(define (f) f)
```
ARC does not support local recursive functions

**Comment by jakerockland** [comment] 2017-12-11 17:27
Hi @zaoqi! Bit confused what the issue is here?

**Comment by jakerockland** [comment] 2017-12-14 00:49
Going to close this for now as I'm not sure what the issue at hand is, can reopen though if you can add a bit more clarification @zaoqi 😅

**Comment by zaoqi-unsafe** [comment] 2017-12-14 10:48
Arc doesn't supports something like it.

**Comment by jakerockland** [comment] 2017-12-14 22:04
Ah, will need to look into this a bit more @zaoqi-unsafe

**Comment by zaoqi** [comment] 2018-01-06 06:51
can combine functions to solve this problem

**Comment by jakerockland** [comment] 2018-01-16 19:55
@zaoqi Unfortunately I am not having the time recently to work on this, but if you have the time to open up a PR, I would very much appreciate it and will review ASAP!

**Comment by jakerockland** [comment] 2018-02-17 01:14
@zaoqi Would you be able to provide a bit more info regarding what you mean by combining functions to fix this?

**Comment by jakerockland** [comment] 2018-05-22 19:39
@zaoqi Wanted to ping you again just to see if you could give a bit more insight to me for fixing this, any resources you can point me in the direction of would be much appreciated!

**Comment by zaoqi** [comment] 2018-05-23 10:06
ARC cannot handle recursion.

I invented a way to solve it.But it may not be suitable for Scheme.

This bug is not important and does not need to be resolved.

**Comment by jakerockland** [comment] 2018-05-23 19:51
@zaoqi Hmm okay thanks so much for shining some light on this! I really appreciate it. Going to close this issue for now then though.

**Closed by jakerockland** 2018-05-23 19:51 UTC
Labels: bug
